### ISSUE TITLE
Could not import settings

### ISSUE THREAD

**Issue by MarkMangoba** [benadida/helios-server#146]
Upon reading install instructions, I was able to get through requirements.txt, but failing upon import of settings file:  Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/helios-server/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/root/helios-server/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/root/helios-server/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/root/helios-server/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/helios-server/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'settings' (Is it on sys.path? Is there an import error in the settings file?): No module named amqp

I checked sys.path and do see /root/helios-server/venv/local/lib/python2.7/site-packages in the path.

**Comment by shirlei** [comment]
Hi Mark, could you detail a bit more the steps you took? Please, use helios voting on google groups:
https://groups.google.com/forum/#!forum/helios-voting

**Comment by benadida** [comment]
Hi @MarkMangoba is this still an issue?

**Comment by benadida** [comment]
seeing no confirmation, closing this.
