### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Nicedude-git** [benadida/helios-server#243]
Hello. I was following the the instructions on INSTALL.md and got the following error after entering the command _source venv/bin/activate_

 ERROR: Command errored out with exit status 1:
     command: /root/helios-server/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-twesmqq0/pyparsing/setup.py'"'"'; __file__='"'"'/tmp/pip-install-twesmqq0/pyparsing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3e5_qwut
         cwd: /tmp/pip-install-twesmqq0/pyparsing/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-twesmqq0/pyparsing/setup.py", line 9, in <module>
        from pyparsing import __version__ as pyparsing_version
      File "/tmp/pip-install-twesmqq0/pyparsing/pyparsing.py", line 855
        except ParseBaseException, err:
                                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Couldn't finish installation.

**Comment by Nicedude-git** [comment]
Fixed.  Virtualenv should not be installed with pip3 as in the docs, but with pip.
